// Соответствие: заголовок колонки в Google Sheet -> имя колонки в Supabase
// Полная таблица соответствия — в файле mapping.md, который прислал Claude
export const COLUMN_MAP: Record<string, string> = {
  "Дата открытия": "data_otkrytiya",
  "Старт потока": "start_potoka",
  "Прошло дней с потока": "proshlo_dney_s_potoka",
  "ФИ ученика": "fi_uchenika",
  "ID VK активная": "id_vk_aktivnaya",
  "ID VK связанные": "id_vk_svyazannye",
  "Номер телефона": "nomer_telefona",
  "VK phone": "vk_phone",
  "ID VK куратора": "id_vk_kuratora",
  "ФИ куратора": "fi_kuratora",
  "ГИА": "gia",
  "Продукты": "produkty",
  "КЛАСС 👍": "klass",
  "Почта": "pochta",
  "Telegram": "telegram",
  "ID платформа": "id_platforma",
  "Статус оплаты": "status_oplaty",
  "Сумма оплаты": "summa_oplaty",
  "Номер телефона с заказа": "nomer_telefona_s_zakaza",
  "Онбординг": "onbording",
  "Нулевой блок": "nulevoy_blok",
  "Письмо в будущее": "pismo_v_budushchee",
  "Профориентация": "proforientatsiya",
  "Карьерьный дневник": "karernyy_dnevnik",
  "Количество продуктов": "kolichestvo_produktov",
  "% активации на продукты": "pct_aktivatsii_na_produkty",
  "Просмотрено уроков": "prosmotreno_urokov",
  "Последний урок": "posledniy_urok",
  "3 (вебы)": "veby_3",
  "7 (вебы)": "veby_7",
  "2нед (вебы)": "veby_2ned",
  "3нед (вебы)": "veby_3ned",
  "4нед (вебы)": "veby_4ned",
  "5нед (вебы)": "veby_5ned",
  "6нед (вебы)": "veby_6ned",
  "7нед (вебы)": "veby_7ned",
  "8нед (вебы)": "veby_8ned",
  "3мес (вебы)": "veby_3mes",
  "4мес (вебы)": "veby_4mes",
  "5+мес (вебы)": "veby_5plusmes",
  "Всего уроков": "vsego_urokov",
  "% просмотра уроков": "pct_prosmotra_urokov",
  "Выполнено ДЗ": "vypolneno_dz",
  "Выполнено ДЗ в тек. мес.": "vypolneno_dz_v_tek_mes",
  "Последнее ДЗ": "poslednee_dz",
  "3 (ДЗ)": "dz_3",
  "7 (ДЗ)": "dz_7",
  "2нед (ДЗ)": "dz_2ned",
  "3нед (ДЗ)": "dz_3ned",
  "4нед (ДЗ)": "dz_4ned",
  "5нед (ДЗ)": "dz_5ned",
  "6нед (ДЗ)": "dz_6ned",
  "7нед (ДЗ)": "dz_7ned",
  "8нед (ДЗ)": "dz_8ned",
  "3мес (ДЗ)": "dz_3mes",
  "4мес (ДЗ)": "dz_4mes",
  "5+мес (ДЗ)": "dz_5plusmes",
  "Всего ДЗ": "vsego_dz",
  "% выполнения ДЗ": "pct_vypolneniya_dz",
};
